# Generated by Django 3.0.3 on 2020-07-14 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contactno', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule_new_course',
            name='date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
